# == Variables ==
# 
# You can define here your project Variables.
# If you want to define/override a Variable for a specific Environment, 
# add an additional ‘variables.yaml’ file in a subdirectory in the ‘Config’ folder: 
# '<project>/Config/_<environment>/variables.yaml
#
Variables:
  # Cron expression define the time to start the cron job: Demo.
  # Refer to http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/tutorial-lesson-06.html
  # An expression to create a trigger that simply fires every 5 seconds
  # Note: Please restart the Ivy Server after changing this variable.
  demoStartCronPattern: 0/5 * * * * ?
